Temporarily disable publish.github setting due to error
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/feedarchive/libera-cryptbot-live (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa8f04a2dc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))